let products = {
  data: [
    {
      productName: "KOLD - Dark Sequence",
      category: "Minimal",
      price: 20,
      image: "./media/al-final-del-tunel-kold.jpg",
      sound: "./media/KOLD - Dark Sequence (Original Mix).mp3",
      id: 1,
    },
    {
      productName: "KOLD - Al Final Del Túnel ",
      category: "Minimal",
      price: 20,
      image: "./media/al-final-del-tunel-kold.jpg",
      sound: "./media/KOLD - Al Final Del Túnel (Original Mix).mp3",
      id: 2,
    },
    {
      productName: "Fenoma - White Lights",
      category: "House",
      price: 20,
      image: "./media/Fenoma-White-Lights-EP.jpg",
      sound: "./media/Fenoma - White Lights (Original Mix).mp3",
      id: 3,
    },
    {
      productName: "Fenoma - Feel It",
      category: "House",
      price: 20,
      image: "./media/Fenoma-White-Lights-EP.jpg",
      sound: "./media/Fenoma - Feel It (Original Mix).mp3",
      id: 4,
    },
    {
      productName: "Anvii - Check This Out",
      category: "House",
      price: 20,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Check This Out (Original Mix).mp3",
      id: 5,
    },
    {
      productName: "Anvii - Rojaiju",
      category: "House",
      price: 20,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Rojaiju (Original Mix).mp3",
      id: 6,
    },
    {
      productName: "Anvii - Making The Groove",
      category: "House",
      price: 20,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
      id: 7,
    },
    {
      productName: "JØKR - All Night Long",
      category: "Minimal",
      price: 20,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound:
        "./media/JØKR - All Night Long (Original Mix) Bandcamp Exclusive.mp3",
      id: 8,
    },
    {
      productName: "JØKR - Headhunter",
      category: "Minimal",
      price: 20,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound: "./media/JØKR - Headhunter (Original Mix) Bandcamp Exclusive.mp3",
      id: 9,
    },
    {
      productName: "JØKR - Ninja",
      category: "Minimal",
      price: 20,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound: "./media/JØKR - Ninja (Original Mix) Bandcamp Exclusive.mp3",
      id: 10,
    },
    {
      productName: "Dark Saw - Ride of hell",
      category: "Minimal",
      price: 20,
      image: "./media/dark saw.jpg",
      sound: "./media/Dark Saw - Rider Of Hell (Original Mix).mp3",
      id: 11,
    },
    {
      productName: "Dark Saw - Sally",
      category: "Minimal",
      price: 20,
      image: "./media/dark saw.jpg",
      sound: "./media/Dark Saw - Sally (Original Mix).mp3",
      id: 12,
    },
    {
      productName: "Eddy JB - Tucibi",
      category: "Minimal",
      price: 20,
      image: "./media/eddy.jpg",
      sound: "./media/Eddy JB - Tucibi (Original Mix).mp3",
      id: 13,
    },
    {
      productName: "Eddy JB - Destroy",
      category: "Minimal",
      price: 20,
      image: "./media/eddy.jpg",
      sound: "./media/Eddy JB - Destroy (Original Mix).mp3",
      id: 13,
    },
  ],
};
