let products = {
  data: [
    {
      productName: "KOLD - Dark Sequence",
      category: "Minimal",
      price: 30,
      image: "./media/al-final-del-tunel-kold.jpg",
      sound: "./media/KOLD - Dark Sequence (Original Mix).mp3",
      id: 1,
    },
    {
      productName: "KOLD - Al Final Del Túnel ",
      category: "Minimal",
      price: 30,
      image: "./media/al-final-del-tunel-kold.jpg",
      sound: "./media/KOLD - Al Final Del Túnel (Original Mix).mp3",
      id: 2,
    },
    {
      productName: "Fenoma - White Lights",
      category: "House",
      price: 30,
      image: "./media/Fenoma-White-Lights-EP.jpg",
      sound: "./media/Fenoma - White Lights (Original Mix).mp3",
      id: 3,
    },
    {
      productName: "Fenoma - Feel It",
      category: "House",
      price: "30",
      image: "./media/Fenoma-White-Lights-EP.jpg",
      sound: "./media/Fenoma - Feel It (Original Mix).mp3",
      id: 4,
    },
    {
      productName: "Anvii - Check This Out",
      category: "House",
      price: 30,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Check This Out (Original Mix).mp3",
      id: 5,
    },
    {
      productName: "Anvii - Rojaiju",
      category: "House",
      price: 49,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Rojaiju (Original Mix).mp3",
      id: 6,
    },
    {
      productName: "Anvii - Making The Groove",
      category: "House",
      price: 99,
      image: "./media/Anvii-Making-the-groove-EP.jpg",
      sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
      id: 7,
    },
    {
      productName: "JØKR - All Night Long",
      category: "Minimal",
      price: 32,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound:
        "./media/JØKR - All Night Long (Original Mix) Bandcamp Exclusive.mp3",
      id: 8,
    },
    {
      productName: "JØKR - Headhunter",
      category: "Minimal",
      price: 129,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound: "./media/JØKR - Headhunter (Original Mix) Bandcamp Exclusive.mp3",
      id: 9,
    },
    {
      productName: "JØKR - Ninja",
      category: "Minimal",
      price: 89,
      image: "./media/jokr-head-hunter-EP.jpg",
      sound: "./media/JØKR - Ninja (Original Mix) Bandcamp Exclusive.mp3",
      id: 10,
    },
    {
      productName: "Brown Men's Jacket",
      category: "Psytrance",
      price: 189,
      image: "brown-jacket.jpg",
      sound: "",
      id: 11,
    },
    {
      productName: "Comfy Gray Pants",
      category: "Psytrance",
      price: 49,
      image: "comfy-gray-pants.jpg",
      sound: "",
      id: 12,
    },
  ],
};
